### ISSUE TITLE
This software is not adhering to the theme of the system.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [flathub/fr.romainvigier.MetadataCleaner#25]
I, and many others, shall not use software that is not able to adhere to the theme of its host operating-system.

**Comment by rmnvgr** [comment]
Thank you for your report. Of course nobody forces you to use applications that do not meet your expectations.

For the record this issue tracker is only used for issues regarding the Flathub packaging of Metadata Cleaner, the issue tracker for the application itself is here: https://gitlab.com/rmnvgr/metadata-cleaner/-/issues

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/fr.romainvigier.MetadataCleaner/issues/25#issuecomment-926183836

I shall report this upstream.
